---
- id: general
  title: General
  data: conf/conf.json
  schema: conf/schema/conf.schema.yaml
- id: style
  title: Styling
  data: conf/style.json
  schema: conf/schema/style.schema.yaml
- id: authors
  title: Authors
  data: conf/authors.json
  schema: conf/schema/authors.schema.yaml
- id: books
  title: Books
  data: conf/published.json
  schema: conf/schema/published.schema.yaml
- id: social
  title: Social
  data: conf/social.yaml
  schema: conf/schema/social.schema.yaml
- id: series
  title: Series
  data: conf/series.yaml
  schema: conf/schema/series.schema.yaml
- id: distributors
  title: Distributors
  data: conf/distributors.json
  schema: conf/schema/distributors.schema.yaml
- id: news
  title: News
  data: conf/news.json
  schema: conf/schema/news.schema.yaml
- id: structure
  data: conf/structure.json
