type: list
elemType: object
nameProp: name
addTitle: author
properties:
  name:
    type: string
    key: true
  socialMediaLinks:
    type: object
    properties:
      name:
        type: string
      url:
        type: url
  image:
      type: image
  imageLink:
      type: string
  content:
      type: text
  external:
      type: boolean
  url:
    type: url
