type: object
properties:
  siteName:
    type: string
    desc: Page title. Appears in the browser window/tab title bar.
  copyrightShort:
    type: string
    desc: Site copyright notice. Appears at the bottom of the page. Narrow format for phone/tablet.
  copyright:
    type: string
    desc: Site copyright notice. Appears at the bottom of the page.

  license:
    type: object
    properties:
      url:
        type: url
        desc: URL for further information about how works on this page are licensed.
      imageUrl:
        type: url
        desc: Page content licensing descriptive image URL.
      description:
        type: string
        desc: Page content license type description

  metadata:
    type: object
    properties:
      ogType:
        type: string
        desc: OpenGraph indentifier for site content. This is mainly relevant to how pages and shared URLs from this site will be categorized on social media sites.
      title:
        type: string
        desc: Default title displayed when site pages are shared on social media sites, unless overriden by more specific content, like for book pages.
      description:
        type: string
        desc: Default description displayed when site pages are shared on social media sites, unless overriden by more specific content, like for book pages.
      image:
        type: image
        desc: Default image displayed when site pages are shared on social media sites, unless overriden by more specific content, like for book pages.
      imageType:
        type: string
        desc: A MIME type for the default site image.
      imageWidth:
        type: number
        desc: Width in pixels for the default site image.
      imageHeight:
        type: number
        desc: Height in pixels for the default site image.

  feedback:
    type: object
    properties:
      description:
        type: string
        desc: Descripton displayed on the site feedback form page.
      subject:
        type: string
        desc: Subject line for emails you'll receive when people use the site feedback form (Maybe? I think this got replaced in the switch to AWS SNS email sending.)
      messages:
        type: list
        elemType: string
        desc: An advanced feature for displaying cusomized contact form content when users click on site items. Only supported in the 'Artist' template for now.

  coverPromoBackground:
    type: image
    desc: Background image used when auto-generating social media promo images for book covers.
  publishedStickerText:
    type: string
    desc: Text to use on the sticker for items on the site available for sale.
  unpublishedStickerText:
    type: string
    desc: Text to use on the sicket for items on the site not currently available for sale.
  socialMediaPageHeader:
    type: text
    desc: Description at the top of the social media sharing/promotions page of the site.

  fbAdminCode:
    type: string
    desc: If you also maintain a facebook page related to this site, you can use it to link shares from this site back to your FB page. Maybe? Depends how Facebook is interpreting this code.
  pintrestCode:
    type: string
    desc: A code used when users share this site URL on Pintrest. It used to make sharing to Pintrest easier. Honestly not sure if this is still useful?
