type: list
elemType: object
nameProp: name
addTitle: distributor
properties:
  id:
    type: string
    hidden: true
  name:
    type: string
  url:
    type: url
  icon:
    type: image
    tag: dist-icons
  featureIcon:
    type: image
  bookIdProp:
    type: string
  popupText:
    type: string
