type: list
elemType: object
nameProp: name
addTitle: distributor
properties:
  id:
    disp: Short Name
    type: string
    desc: Short name (code) to be used for this distributor. Used in Book defentions for Primary Distributor field.
  name:
    disp: Display Name
    type: string
    desc: Display name to be used for this distributor.
  url:
    disp: Buy Link URL
    type: url
    desc: Base URL to be used when crafting 'buy' links for this distributor. The '@BOOKID@' varaible in this URL will be replaced by the distributor specific ID configured for each book.
  icon:
    disp: Icon
    type: image
    desc: Icon to be used for this distributor on site pages. Should be fairly small (lke 100x100 pixels, for example.)
    tag: dist-icons
  featureIcon:
    disp: Feature Icon
    type: image
    desc: A larger icon image for this distributor, if needed, for use on larger-format book pages, though really the same small icon image can be used.
  bookIdProp:
    disp: Book Property Name
    type: string
    desc: Links to the book property of this same name that holds the distributor specfic ID.
  popupText:
    disp: Tooltip
    type: string
    desc: Popup (tooltip) text that will be shown when the user hovers over the distributor icon.
