type: list
elemType: object
nameProp: title
addTitle: post
properties:
  id:
    type: string
    hidden: true
  title:
    type: string
  type:
    type: list
    elemType: string
    closed: true
    values:
      - post
    hidden: true
  format:
    type: list
    elemType: string
    closed: true
    values:
      - standard
    hidden: true
  status:
    type: list
    elemType: string
    closed: true
    values:
      - hidden
      - publish
  publishedDateIso:
    type: string
  publishedDateDisplay:
    type: string
  category:
    type: list
    elemType: string
  author:
    type: string
  content:
    type: text
