type: list
elemType: object
nameProp: name
addTitle: promotion
properties:
  name:
    type: string
    key: true
  promoUrl:
    type: url
  image:
    type: image
  imageHeight:
    type: number
  imageWidth:
    type: number
