type: list
elemType: object
nameProp: name
addTitle: promotion
properties:
  name:
    type: string
    key: true
  enabled:
    type: boolean
  promoUrl:
    type: url
  image:
    type: image
  imageHeight:
    type: number
  imageWidth:
    type: number
  categories:
    type: list
    elemType: string
