type: list
elemType: object
nameProp: name
addTitle: promotion
properties:
  name:
    type: string
    key: true
  text:
    type: string
  altText:
    type: string
  enabled:
    type: boolean
  targetUrl:
    type: url
  image:
    type: image
  keywords:
    type: list
    elemType: string
  imageHeight:
    type: number
  imageWidth:
    type: number
  categories:
    type: list
    elemType: string
